In [1]:
#importing of required libraries

import pandas as pd
import matplotlib.pylab as plt
import numpy as np

In [2]:
# importing of required dataset
df=pd.read_csv('assignment-1.csv')
df.head()

,City,State,Country,Weather,Geoposoition,Season,WindSpeed (Km/h)
0,Vancouver,Washington,Canada,Snow,Seashore,Rainy,18
1,Portland,Oregon,United States,Thunder,Plain,Autumn,14
2,San Francisco,California,United States,fog,Seashore,Autumn,13
3,Seattle,Washington,United States,Snow,Seashore,Autumn,13
4,Pachuca,Hidalgo,Mexico,fog,Central,Rainy,19

In [3]:
# using the PIVOT technique to categorize cities based on similar weather

df1=df.pivot(columns="Weather",values="City")
df1.fillna('-',inplace=True) # filling Nan to -
# saving the obtained data drame to df1
df1.to_csv('C:\\Users\\DELL\\Desktop\\MY STUFF\DATA SCIENCE\DATA\\Raw data\\similar_weather_cities.csv')

In [4]:
# displaying of all cities that have similar weather characteristics

df1=pd.read_csv('C:\\Users\\DELL\\Desktop\\MY STUFF\DATA SCIENCE\DATA\\Raw data\\similar_weather_cities.csv')
df1.drop('Unnamed: 0',axis=1,inplace=True)
df1

,Cloudy,Rainy,Snow,Sunny,Thunder,Windy,fog
0,-,-,Vancouver,-,-,-,-
1,-,-,-,-,Portland,-,-
2,-,-,-,-,-,-,San Francisco
3,-,-,Seattle,-,-,-,-
4,-,-,-,-,-,-,Pachuca
5,San Diego,-,-,-,-,-,-
6,-,-,-,-,-,-,Toronto
7,-,-,-,-,-,-,Philadelphia
8,-,-,-,-,-,Montreal,-
9,-,-,-,-,-,-,Boston
10,-,-,-,Guadalajara,-,-,-
11,-,-,Calgary,-,-,-,-
12,-,Victoria,-,-,-,-,-
13,-,-,-,Merida,-,-,-

In [9]:
#Using by the groupby  techniqueto display all cities of a particular country and display their weather characteristics

df2=df.groupby(['Country', 'City', 'Weather'], observed=True).count()
columns=['State','Geoposoition','Season','WindSpeed (Km/h)']
df2.drop(columns,axis=1,inplace=True)
df2

Empty DataFrame
Columns: []
Index: [(Canada, Calgary, Snow), (Canada, Montreal, Windy), (Canada, Toronto, fog), (Canada, Vancouver, Snow), (Canada, Victoria, Rainy), (Mexico, Guadalajara, Sunny), (Mexico, Merida, Sunny), (Mexico, Pachuca, fog), (United States, Boston, fog), (United States, Philadelphia, fog), (United States, Portland, Thunder), (United States, San Diego, Cloudy), (United States, San Francisco, fog), (United States, Seattle, Snow)]

In [6]:
# saving the obtained datadrame df2
df2.to_csv('C:\\Users\\DELL\\Desktop\\MY STUFF\DATA SCIENCE\DATA\\Raw data\\country_cities_weather.csv')

In [7]:
# displaying of all cities of a particular country and display their weather characteristics

df2=pd.read_csv('C:\\Users\\DELL\\Desktop\\MY STUFF\DATA SCIENCE\DATA\\Raw data\\country_cities_weather.csv')
df2

          Country           City  Weather
0          Canada        Calgary     Snow
1          Canada       Montreal    Windy
2          Canada        Toronto      fog
3          Canada      Vancouver     Snow
4          Canada       Victoria    Rainy
5          Mexico    Guadalajara    Sunny
6          Mexico         Merida    Sunny
7          Mexico        Pachuca      fog
8   United States         Boston      fog
9   United States   Philadelphia      fog
10  United States       Portland  Thunder
11  United States      San Diego   Cloudy
12  United States  San Francisco      fog
13  United States        Seattle     Snow